[package]
name = "router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.8"
env_logger = "0.9.0"
log = "0.4.16"
pcap = "0.9.1"
signal-child = "1.0.5"
