[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
accumulator = { path = "../accumulator" }
env_logger = "0.9.0"
log = "0.4.16"
num-bigint = "0.4.3"
